### ISSUE TITLE
Editor does not scroll when cursor is placed offscreen

### ISSUE THREAD

**Issue by markbao** [cjwirth/RichEditorView#77]
When the cursor goes offscreen, and/or when text is typed offscreen, the editor does not move. This doesn't seem like an easy one to solve because of the difficulty of interfacing between the view and the HTML, but wanted to open this to think about potential solutions.

![scroll](https://cloud.githubusercontent.com/assets/27594/16930193/e5e15550-4cef-11e6-907d-22bc83886e30.gif)

**Comment by cjwirth** [comment]
This is actually fixed in the `develop` branch.
I think it should be good enough to use. I haven't fully tested it, so I've been kind of holding off on merging it, even thought I think it's _probably_ fine to use.

Maybe give it a shot? 😃 👍

**Comment by ahoang** [comment]
+1. I pulled the latest commit from develop and I still see the same issue.

**Comment by terenzeyuen** [comment]
Is this merged to master yet? @cjwirth @markbao

**Comment by EmperiorEric** [comment]
Doesn't look like this is merged yet?

**Comment by EmperiorEric** [comment]
Actually the original fix might be in and working. But there is a related bug causing similar issues if the scrollView is screenSize with contentInset so its content appears under the keyboard as opposed to changing the size of the scrollView. Looks like its not taking into account contentInsets when checking `scrollCaretToVisible()`.

This `if visiblePosition + cursorHeight > scrollView.bounds.size.height {` check needs to take into account `scrollView.contentInset.bottom` by subtracting it from the height from what I can see.

**Comment by cjwirth** [comment]
Sorry I'm super unresponsive and everything -- I certainly don't give this project the love it probably needs.

Anyway, check out the latest master, it should have some things that weren't in it before (although it's all Swift 3 now.)

**Comment by EmperiorEric** [comment]
No worries. It does work on master. but we're stuck with Swift 2.3 at the moment. I submitted a PR just for the Swift 2.3 branch if you want to accept that. But otherwise hopefully we'll be moving to Swift 3 soon. 🤞

**Comment by cjwirth** [comment]
I'm not sure if this is still an issue or not, but I made a super thread for scrolling issues. Sorry, but I think I'm going to close this one.

**Comment by Srinivasan27** [comment]
Is fix available for this? @EmperiorEric @cjwirth
